- name: Install base packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - python-pip
  tags:
    - install
    - install:base

- name: Create the hosts file for all machines
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags:
    - install
    - install:base
